/**
 * 環境変数dev
 */
export const environment = {
    production: false,
    APP_PREFIX: 'OY',
    PROJECT_ID: 'oyatsu',
    ENV: 'test',
    ENTRANCE_SERVER_URL: '',
    WAITER_SERVER_URL: '',
    VIEW_TYPE: 'event',
    ANALYTICS_ID: 'UA-139126612-1',
    STORAGE_NAME: 'OYATSU-FRONTEND-STATE',
    STORAGE_TYPE: 'sessionStorage',
    BASE_URL: '/purchase/root',
    LANGUAGE: ['ja'],
    PORTAL_SITE_URL: 'http://oyatsu.town',
    DISPLAY_TICKETED_SEAT: false,
    HEADER_MENU: true,
    HEADER_MENU_SCOPE: ['purchase', 'inquiry'],
    FOOTER_COMPANY_URL: 'http://oyatsu.town/company',
    FOOTER_LAW_URL: 'http://oyatsu.town',
    FOOTER_PRIVACY_POLICY_URL: 'http://oyatsu.town/privacy',
    PURCHASE_CART_MAX_LENGTH: '99',
    PURCHASE_TRANSACTION_TIME: '30',
    PURCHASE_PRE_SCHEDULE_DATE: '3',
    PURCHASE_SCHEDULE_DEFAULT_SELECTED_DATE: '1',
    PURCHASE_SCHEDULE_DISPLAY_LENGTH: '10',
    PURCHASE_SCHEDULE_STATUS_WINDOW_TIME_MINUTES: '-20',
    PURCHASE_SCHEDULE_STATUS_THRESHOLD_VALUE: '30',
    PURCHASE_SCHEDULE_STATUS_THRESHOLD_UNIT: '%',
    PURCHASE_COMPLETE_MAIL_CUSTOM: true,
    INQUIRY_CANCEL: false,
    INQUIRY_QRCODE: false,
    INQUIRY_PRINT: false,
    PRINT_QR_CODE_TYPE: 'encryption'
};
